var $intern_2792 = ')\u3002', $intern_2796 = '<\/strong> \u4E0D\u5141\u8BB8\u4E0A\u4F20\u3002', $intern_2791 = '<\/strong> \u8D85\u8FC7\u5141\u8BB8\u7684\u6700\u5927\u9650\u5236 (', $intern_2787 = '<\/strong>\u3002', $intern_2781 = '<a target="_blank" href="http://support.sitecake.com/anonymous_requests/new">\u63D0\u4EA4<\/a>\u53D1\u73B0\u7684\u95EE\u9898\u4EE5\u4FBF\u6211\u4EEC\u505A\u5F97\u66F4\u597D\uFF0C\u8BF7\u60A8\u9644\u4E0A\u4E0B\u9762\u7684\u9519\u8BEF\u62A5\u544A\u3002\u60A8\u53EF\u4EE5<a href="javascript:location.reload()">\u5237\u65B0<\/a>\u6B64\u9875\u9762\u7EE7\u7EED\u7F16\u8F91\u3002', $intern_2814 = 'AsyncLoader14', $intern_2780 = 'CMS\u51FA\u9519\u4E86\uFF01', $intern_2815 = 'MessagesZhCn_', $intern_2777 = 'runCallbacks14', $intern_2794 = '\u3002', $intern_2812 = '\u4E0A\u4F20\uFF1A', $intern_2789 = '\u4ECE\u670D\u52A1\u5668\u6536\u5230\u65E0\u6548\u54CD\u5E94', $intern_2782 = '\u4FDD\u5B58\u5185\u5BB9\u66F4\u6539\u51FA\u9519\u3002\u91CD\u8BD5...', $intern_2783 = '\u53D1\u5E03\u5185\u5BB9\u51FA\u73B0\u9519\u8BEF\u3002', $intern_2786 = '\u53D1\u73B0\u65E0\u6548\u914D\u7F6E\u53C2\u6570\uFF1A<strong>', $intern_2806 = '\u53D1\u8868', $intern_2785 = '\u6240\u6709\u5185\u5BB9\u66F4\u6539\u5C1D\u8BD5\u90FD\u5931\u8D25\u4E86\u3002', $intern_2784 = '\u6587\u4EF6\u4E0A\u4F20\u51FA\u9519\u4E86\u3002', $intern_2801 = '\u66F4\u591A', $intern_2811 = '\u672A\u88AB\u6355\u6349\u5F02\u5E38', $intern_2788 = '\u6839\u636E\u5236\u5B9A\u4EE3\u7801\u751F\u6210\u5730\u56FE\u5931\u8D25\u3002', $intern_2797 = '\u6839\u636E\u6307\u5B9A\u4EE3\u7801\u6216\u94FE\u63A5\u751F\u6210\u89C6\u9891\u5931\u8D25\u3002', $intern_2813 = '\u68C0\u6D4B\u5230\u65B0\u7684CMS\u66F4\u65B0\u53D1\u5E03<a href=http://sitecake.com/download.html target=_blank>\u94FE\u63A5<\/a> (', $intern_2803 = '\u70B9\u51FB\u52A0\u5165\u81EA\u5B9A\u4E49 HTML', $intern_2800 = '\u70B9\u51FB\u5F00\u59CB\u7F16\u8F91', $intern_2802 = '\u70B9\u51FB\u63D2\u5165Flash', $intern_2804 = '\u70B9\u51FB\u63D2\u5165Google\u5730\u56FE', $intern_2805 = '\u70B9\u51FB\u63D2\u5165\u89C6\u9891', $intern_2779 = '\u7F3A\u7701\u6837\u5F0F', $intern_2799 = '\u7F51\u9875\u94FE\u63A5', $intern_2778 = '\u8FD8\u6709\u66F4\u6539\u5C1A\u672A\u4FDD\u5B58\uFF0C\u8981\u7EE7\u7EED\u5417\uFF1F', $intern_2790 = '\u9009\u5B9A\u4E0A\u4F20\u6587\u4EF6 <strong>', $intern_2795 = '\u9009\u5B9A\u6587\u4EF6 <strong>', $intern_2793 = '\u9009\u5B9A\u7684\u4E0A\u4F20\u6587\u4EF6\u65E0\u6548\uFF1A', $intern_2809 = '\u9009\u62E9\u4E00\u4E2A\u6216\u591A\u4E2A\u56FE\u7247\u4E0A\u4F20', $intern_2808 = '\u9009\u62E9\u4E00\u4E2A\u6216\u591A\u4E2A\u6587\u4EF6\u4E0A\u4F20', $intern_2810 = '\u9009\u62E9\u4E00\u4E2A\u6216\u591A\u4E2A\u89C6\u9891\u4E0A\u4F20', $intern_2807 = '\u9009\u62E9\u4E00\u4E2A\u6216\u591A\u4E2A\u97F3\u9891\u4E0A\u4F20', $intern_2798 = '\u90AE\u4EF6\u5730\u5740';
function com_google_gwt_lang_asyncloaders_AsyncLoader14_$runCallbacks__Lcom_google_gwt_lang_asyncloaders_AsyncLoader14_2V(){
  var $e0, e, handler, next;
  while (com_google_gwt_lang_asyncloaders_AsyncLoader14_callbacksHead) {
    handler = com_google_gwt_core_client_GWT_sUncaughtExceptionHandler;
    next = com_google_gwt_lang_asyncloaders_AsyncLoader14_callbacksHead;
    com_google_gwt_lang_asyncloaders_AsyncLoader14_callbacksHead = com_google_gwt_lang_asyncloaders_AsyncLoader14_callbacksHead.com_google_gwt_lang_asyncloaders_AsyncLoader14_1_1Callback_next;
    !com_google_gwt_lang_asyncloaders_AsyncLoader14_callbacksHead && (com_google_gwt_lang_asyncloaders_AsyncLoader14_callbacksTail = null);
    if (!handler) {
      com_sitecake_contentmanager_client_resources_LocaleProxyImpl$14_$onSuccess__Lcom_sitecake_contentmanager_client_resources_LocaleProxyImpl$14_2V(next.com_google_gwt_lang_asyncloaders_AsyncLoader14_1_1Callback_callback);
    }
     else {
      try {
        com_sitecake_contentmanager_client_resources_LocaleProxyImpl$14_$onSuccess__Lcom_sitecake_contentmanager_client_resources_LocaleProxyImpl$14_2V(next.com_google_gwt_lang_asyncloaders_AsyncLoader14_1_1Callback_callback);
      }
       catch ($e0) {
        $e0 = com_google_gwt_lang_Exceptions_caught__Ljava_lang_Object_2Ljava_lang_Object_2($e0);
        if (com_google_gwt_lang_Cast_instanceOf__Ljava_lang_Object_2IZ($e0, 67)) {
          e = $e0;
          handler.onUncaughtException__Ljava_lang_Throwable_2V(e);
        }
         else 
          throw $e0;
      }
    }
  }
}

function com_google_gwt_lang_asyncloaders_AsyncLoader14_AsyncLoader14__V(){
}

function com_google_gwt_lang_asyncloaders_AsyncLoader14_onLoad__V(){
  com_google_gwt_lang_asyncloaders_AsyncLoader14_instance = new com_google_gwt_lang_asyncloaders_AsyncLoader14_AsyncLoader14__V;
  com_google_gwt_core_client_impl_AsyncFragmentLoader_$fragmentHasLoaded__Lcom_google_gwt_core_client_impl_AsyncFragmentLoader_2IV((com_google_gwt_core_client_impl_AsyncFragmentLoader_$clinit__V() , com_google_gwt_core_client_impl_AsyncFragmentLoader_BROWSER_1LOADER), 14);
  !!$stats && $stats(com_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_$createStatsEvent__Lcom_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_2Ljava_lang_String_2Ljava_lang_String_2IILcom_google_gwt_core_client_JavaScriptObject_2($intern_2777, $intern_149, -1, -1));
  com_google_gwt_lang_asyncloaders_AsyncLoader14_instance.runCallbacks__V();
  !!$stats && $stats(com_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_$createStatsEvent__Lcom_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_2Ljava_lang_String_2Ljava_lang_String_2IILcom_google_gwt_core_client_JavaScriptObject_2($intern_2777, $intern_2355, -1, -1));
}

function com_google_gwt_lang_asyncloaders_AsyncLoader14(){
}

_ = com_google_gwt_lang_asyncloaders_AsyncLoader14_AsyncLoader14__V.prototype = com_google_gwt_lang_asyncloaders_AsyncLoader14.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_google_gwt_lang_asyncloaders_AsyncLoader14_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1google_1gwt_1lang_1asyncloaders_1AsyncLoader14_12_1classLit;
}
;
_.runCallbacks__V = function com_google_gwt_lang_asyncloaders_AsyncLoader14_runCallbacks__V(){
  com_google_gwt_lang_asyncloaders_AsyncLoader14_$runCallbacks__Lcom_google_gwt_lang_asyncloaders_AsyncLoader14_2V();
}
;
_.java_lang_Object_castableTypeMap$ = {};
function com_sitecake_contentmanager_client_resources_LocaleProxyImpl$14_$onSuccess__Lcom_sitecake_contentmanager_client_resources_LocaleProxyImpl$14_2V(this$static){
  this$static.com_sitecake_contentmanager_client_resources_LocaleProxyImpl$14_this$0.com_sitecake_contentmanager_client_resources_LocaleProxyImpl_messages = new com_sitecake_contentmanager_client_resources_MessagesZhCn_1_MessagesZhCn_1__V;
  com_sitecake_commons_client_util_SynchronizationBarrier_$release__Lcom_sitecake_commons_client_util_SynchronizationBarrier_2V(this$static.com_sitecake_contentmanager_client_resources_LocaleProxyImpl$14_this$0.com_sitecake_contentmanager_client_resources_LocaleProxyImpl_synchronizationBarrier);
}

function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_MessagesZhCn_1__V(){
}

function com_sitecake_contentmanager_client_resources_MessagesZhCn_1(){
}

_ = com_sitecake_contentmanager_client_resources_MessagesZhCn_1_MessagesZhCn_1__V.prototype = com_sitecake_contentmanager_client_resources_MessagesZhCn_1.prototype = new java_lang_Object;
_.confirmUnsafeLogout__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_confirmUnsafeLogout__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2778).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.defaultStyle__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_defaultStyle__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2779).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.errorMessage1__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_errorMessage1__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2780).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.errorMessage2__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_errorMessage2__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2781).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.failedAttemptToSaveContent__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_failedAttemptToSaveContent__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2782).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.failedToPublishContent__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_failedToPublishContent__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2783).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.failedToUploadFiles__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_failedToUploadFiles__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2784).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.getClass__Ljava_lang_Class_2$ = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1sitecake_1contentmanager_1client_1resources_1MessagesZhCn_11_12_1classLit;
}
;
_.giveUpContentSaving__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_giveUpContentSaving__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2785).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidConfigParameter__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_invalidConfigParameter__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2(arg0, arg1){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2786), arg0), $intern_163), arg1), $intern_2787).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidMapInputCode__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_invalidMapInputCode__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2788).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidServiceResponse__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_invalidServiceResponse__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2789).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidUploadFileMaxSize__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_invalidUploadFileMaxSize__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2(arg0, arg1){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2790), arg0), $intern_2791), arg1), $intern_2792).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidUploadFileSelection__Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_invalidUploadFileSelection__Ljava_lang_String_2Ljava_lang_String_2(arg0){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2793), arg0), $intern_2794).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidUploadFileType__Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_invalidUploadFileType__Ljava_lang_String_2Ljava_lang_String_2(arg0){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2795), arg0), $intern_2796).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidVideoInputCode__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_invalidVideoInputCode__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2797).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.linkEditorMailtoLink__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_linkEditorMailtoLink__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2798).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.linkEditorWebLink__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_linkEditorWebLink__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2799).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.newTextItemDefaultContent__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_newTextItemDefaultContent__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2800).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.notificationDialogReadMore__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_notificationDialogReadMore__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2801).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteFlash__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_pasteFlash__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2802).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteHtml__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_pasteHtml__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2803).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteMap__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_pasteMap__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2804).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteVideo__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_pasteVideo__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2805).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.publishButton__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_publishButton__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2806).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadAudio__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_selectFilesToUploadAudio__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2807).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadGeneric__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_selectFilesToUploadGeneric__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2808).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadImage__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_selectFilesToUploadImage__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2809).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadVideo__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_selectFilesToUploadVideo__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2810).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.uncaughtException__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_uncaughtException__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2811).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.uploadingFiles__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_uploadingFiles__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2812).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.versionUpdateMessage__Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesZhCn_1_versionUpdateMessage__Ljava_lang_String_2Ljava_lang_String_2(arg0){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2813), arg0), $intern_2370).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.java_lang_Object_castableTypeMap$ = {};
var com_google_gwt_lang_ClassLiteralHolder_Lcom_1google_1gwt_1lang_1asyncloaders_1AsyncLoader14_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_1728, $intern_2814), com_google_gwt_lang_ClassLiteralHolder_Lcom_1sitecake_1contentmanager_1client_1resources_1MessagesZhCn_11_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_2116, $intern_2815);
$entry(com_google_gwt_lang_asyncloaders_AsyncLoader14_onLoad__V)();
