var $intern_2719 = ' \xE9 inv\xE1lido.', $intern_2717 = '<\/strong>, o limite m\xE1ximo permitido \xE9 de (', $intern_2709 = 'Ajude-nos a corrigir este problema nos dizendo <a target="_blank" href="http://suporte.sitecake.com.br/solicitacoes_anonimas/nova">o que aconteceu<\/a>. Por favor inclua o relat\xF3rio abaixo. Para continuar editando apenas <a href="javascript:location.reload()">atualize<\/a> a p\xE1gina.', $intern_2736 = 'AsyncLoader11', $intern_2737 = 'MessagesPtBr_', $intern_2715 = 'N\xE3o foi poss\xEDvel adicionar um mapa a partir dos dados fornecidos.', $intern_2722 = 'N\xE3o foi poss\xEDvel adicionar um v\xEDdeo a partir dos dados fornecidos.', $intern_2713 = 'Todas as ultimas tentativas de salvar as modifica\xE7\xF5es de conte\xFAdo falharam.', $intern_2735 = 'Uma nova vers\xE3o do CMS <a href=http://sitecake.com.br/download target=_blank>est\xE1 dispon\xEDvel<\/a> (', $intern_2705 = 'runCallbacks11';
function com_google_gwt_lang_asyncloaders_AsyncLoader11_$runCallbacks__Lcom_google_gwt_lang_asyncloaders_AsyncLoader11_2V(){
  var $e0, e, handler, next;
  while (com_google_gwt_lang_asyncloaders_AsyncLoader11_callbacksHead) {
    handler = com_google_gwt_core_client_GWT_sUncaughtExceptionHandler;
    next = com_google_gwt_lang_asyncloaders_AsyncLoader11_callbacksHead;
    com_google_gwt_lang_asyncloaders_AsyncLoader11_callbacksHead = com_google_gwt_lang_asyncloaders_AsyncLoader11_callbacksHead.com_google_gwt_lang_asyncloaders_AsyncLoader11_1_1Callback_next;
    !com_google_gwt_lang_asyncloaders_AsyncLoader11_callbacksHead && (com_google_gwt_lang_asyncloaders_AsyncLoader11_callbacksTail = null);
    if (!handler) {
      com_sitecake_contentmanager_client_resources_LocaleProxyImpl$11_$onSuccess__Lcom_sitecake_contentmanager_client_resources_LocaleProxyImpl$11_2V(next.com_google_gwt_lang_asyncloaders_AsyncLoader11_1_1Callback_callback);
    }
     else {
      try {
        com_sitecake_contentmanager_client_resources_LocaleProxyImpl$11_$onSuccess__Lcom_sitecake_contentmanager_client_resources_LocaleProxyImpl$11_2V(next.com_google_gwt_lang_asyncloaders_AsyncLoader11_1_1Callback_callback);
      }
       catch ($e0) {
        $e0 = com_google_gwt_lang_Exceptions_caught__Ljava_lang_Object_2Ljava_lang_Object_2($e0);
        if (com_google_gwt_lang_Cast_instanceOf__Ljava_lang_Object_2IZ($e0, 67)) {
          e = $e0;
          handler.onUncaughtException__Ljava_lang_Throwable_2V(e);
        }
         else 
          throw $e0;
      }
    }
  }
}

function com_google_gwt_lang_asyncloaders_AsyncLoader11_AsyncLoader11__V(){
}

function com_google_gwt_lang_asyncloaders_AsyncLoader11_onLoad__V(){
  com_google_gwt_lang_asyncloaders_AsyncLoader11_instance = new com_google_gwt_lang_asyncloaders_AsyncLoader11_AsyncLoader11__V;
  com_google_gwt_core_client_impl_AsyncFragmentLoader_$fragmentHasLoaded__Lcom_google_gwt_core_client_impl_AsyncFragmentLoader_2IV((com_google_gwt_core_client_impl_AsyncFragmentLoader_$clinit__V() , com_google_gwt_core_client_impl_AsyncFragmentLoader_BROWSER_1LOADER), 11);
  !!$stats && $stats(com_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_$createStatsEvent__Lcom_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_2Ljava_lang_String_2Ljava_lang_String_2IILcom_google_gwt_core_client_JavaScriptObject_2($intern_2705, $intern_144, -1, -1));
  com_google_gwt_lang_asyncloaders_AsyncLoader11_instance.runCallbacks__V();
  !!$stats && $stats(com_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_$createStatsEvent__Lcom_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_2Ljava_lang_String_2Ljava_lang_String_2IILcom_google_gwt_core_client_JavaScriptObject_2($intern_2705, $intern_2360, -1, -1));
}

function com_google_gwt_lang_asyncloaders_AsyncLoader11(){
}

_ = com_google_gwt_lang_asyncloaders_AsyncLoader11_AsyncLoader11__V.prototype = com_google_gwt_lang_asyncloaders_AsyncLoader11.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_google_gwt_lang_asyncloaders_AsyncLoader11_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1google_1gwt_1lang_1asyncloaders_1AsyncLoader11_12_1classLit;
}
;
_.runCallbacks__V = function com_google_gwt_lang_asyncloaders_AsyncLoader11_runCallbacks__V(){
  com_google_gwt_lang_asyncloaders_AsyncLoader11_$runCallbacks__Lcom_google_gwt_lang_asyncloaders_AsyncLoader11_2V();
}
;
_.java_lang_Object_castableTypeMap$ = {};
function com_sitecake_contentmanager_client_resources_LocaleProxyImpl$11_$onSuccess__Lcom_sitecake_contentmanager_client_resources_LocaleProxyImpl$11_2V(this$static){
  this$static.com_sitecake_contentmanager_client_resources_LocaleProxyImpl$11_this$0.com_sitecake_contentmanager_client_resources_LocaleProxyImpl_messages = new com_sitecake_contentmanager_client_resources_MessagesPtBr_1_MessagesPtBr_1__V;
  com_sitecake_commons_client_util_SynchronizationBarrier_$release__Lcom_sitecake_commons_client_util_SynchronizationBarrier_2V(this$static.com_sitecake_contentmanager_client_resources_LocaleProxyImpl$11_this$0.com_sitecake_contentmanager_client_resources_LocaleProxyImpl_synchronizationBarrier);
}

function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_MessagesPtBr_1__V(){
}

function com_sitecake_contentmanager_client_resources_MessagesPtBr_1(){
}

_ = com_sitecake_contentmanager_client_resources_MessagesPtBr_1_MessagesPtBr_1__V.prototype = com_sitecake_contentmanager_client_resources_MessagesPtBr_1.prototype = new java_lang_Object;
_.confirmUnsafeLogout__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_confirmUnsafeLogout__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2706).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.defaultStyle__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_defaultStyle__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2707).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.errorMessage1__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_errorMessage1__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2708).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.errorMessage2__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_errorMessage2__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2709).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.failedAttemptToSaveContent__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_failedAttemptToSaveContent__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2710).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.failedToPublishContent__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_failedToPublishContent__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2711).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.failedToUploadFiles__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_failedToUploadFiles__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2712).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.getClass__Ljava_lang_Class_2$ = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1sitecake_1contentmanager_1client_1resources_1MessagesPtBr_11_12_1classLit;
}
;
_.giveUpContentSaving__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_giveUpContentSaving__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2713).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidConfigParameter__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_invalidConfigParameter__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2(arg0, arg1){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2714), arg0), $intern_160), arg1), $intern_2370).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidMapInputCode__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_invalidMapInputCode__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2715).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidServiceResponse__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_invalidServiceResponse__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2372).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidUploadFileMaxSize__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_invalidUploadFileMaxSize__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2(arg0, arg1){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2716), arg0), $intern_2717), arg1), $intern_2375).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidUploadFileSelection__Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_invalidUploadFileSelection__Ljava_lang_String_2Ljava_lang_String_2(arg0){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2718), arg0), $intern_2719).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidUploadFileType__Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_invalidUploadFileType__Ljava_lang_String_2Ljava_lang_String_2(arg0){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2720), arg0), $intern_2721).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidVideoInputCode__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_invalidVideoInputCode__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2722).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.linkEditorMailtoLink__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_linkEditorMailtoLink__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2452).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.linkEditorWebLink__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_linkEditorWebLink__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2453).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.newTextItemDefaultContent__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_newTextItemDefaultContent__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2723).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.notificationDialogReadMore__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_notificationDialogReadMore__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2724).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteFlash__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_pasteFlash__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2725).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteHtml__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_pasteHtml__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2726).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteMap__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_pasteMap__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2727).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteVideo__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_pasteVideo__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2728).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.publishButton__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_publishButton__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2460).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadAudio__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_selectFilesToUploadAudio__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2729).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadGeneric__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_selectFilesToUploadGeneric__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2730).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadImage__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_selectFilesToUploadImage__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2731).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadVideo__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_selectFilesToUploadVideo__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2732).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.uncaughtException__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_uncaughtException__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2733).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.uploadingFiles__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_uploadingFiles__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2734).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.versionUpdateMessage__Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesPtBr_1_versionUpdateMessage__Ljava_lang_String_2Ljava_lang_String_2(arg0){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2735), arg0), $intern_2375).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.java_lang_Object_castableTypeMap$ = {};
var com_google_gwt_lang_ClassLiteralHolder_Lcom_1google_1gwt_1lang_1asyncloaders_1AsyncLoader11_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_1734, $intern_2736), com_google_gwt_lang_ClassLiteralHolder_Lcom_1sitecake_1contentmanager_1client_1resources_1MessagesPtBr_11_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_2121, $intern_2737);
$entry(com_google_gwt_lang_asyncloaders_AsyncLoader11_onLoad__V)();
