var $intern_2485 = '<\/strong> ist f\xFCr den Upload nicht erlaubt.', $intern_2482 = '<\/strong> \xFCberschreitet die maximal erlaubte Dateigr\xF6\xDFe (', $intern_2478 = 'Alle Versuche die letzten \xC4nderungen zu speichern sind gescheitert.', $intern_2501 = 'AsyncLoader4', $intern_2494 = 'Audiodatei(en) zum Hochladen ausw\xE4hlen', $intern_2496 = 'Bild(er) zum Hochladen ausw\xE4hlen', $intern_2473 = 'CMS hat ein Problem festgestellt!', $intern_2475 = 'Das Speichern der \xC4nderungen ist fehlgeschlagen. Versuche es erneut...', $intern_2495 = 'Datei(en) zum Hochladen ausw\xE4hlen', $intern_2484 = 'Der ausgew\xE4hlte Dateityp <strong>', $intern_2481 = 'Die Gr\xF6\xDFe der ausgew\xE4hlten Datei <strong>', $intern_2483 = 'Die ausgew\xE4hlte Datei ist ung\xFCltig oder defekt ', $intern_2500 = 'Eine neue Version von CMS ist <a href=http://sitecake.com/download.html target=_blank>verf\xFCgbar<\/a> (', $intern_2471 = 'Es wurden nicht alle \xC4nderungen gespeichert. Sind Sie sicher, dass Sie fortfahren m\xF6chten?', $intern_2474 = 'Hilf uns den Fehler zu beheben und <a target="_blank" href="http://support.sitecake.com/anonymous_requests/new">berichte uns was passiert ist<\/a>. Bitte f\xFCge den Bericht von unten hinzu. Du kannst weiter editieren in dem du einfach die Seite <a href="javascript:location.reload()">neul\xE4dst<\/a>.', $intern_2499 = 'Hochladen:', $intern_2489 = 'Klicken um Flash einzuf\xFCgen', $intern_2491 = 'Klicken um Google Map einzuf\xFCgen', $intern_2492 = 'Klicken um Video einzuf\xFCgen', $intern_2490 = 'Klicken um eigenes HTML einzuf\xFCgen', $intern_2480 = 'Konnte kein Karten Objekt erzeugen. Ist der Code oder die URL g\xFCltig?', $intern_2486 = 'Konnte kein Video Objekt erzeugen. Ist der Code oder die URL g\xFCltig?', $intern_2502 = 'MessagesDe_', $intern_2498 = 'Nicht abgefangener Ausnahmefehler', $intern_2472 = 'Standard Design', $intern_2493 = 'Ver\xF6ffent.', $intern_2497 = 'Video(s) zum Hochladen ausw\xE4hlen', $intern_2488 = 'Weiterlesen', $intern_2477 = 'W\xE4hrend dem Dateiupload ist ein Fehler aufgetreten.', $intern_2476 = 'W\xE4hrend dem Ver\xF6ffentlichungs-Vorgang ist ein Fehler aufgetreten.', $intern_2487 = 'Zum Bearbeiten klicken', $intern_2470 = 'runCallbacks4', $intern_2479 = '\xDCng\xFCltige Einstellung gefunden <strong>';
function com_google_gwt_lang_asyncloaders_AsyncLoader4_$runCallbacks__Lcom_google_gwt_lang_asyncloaders_AsyncLoader4_2V(){
  var $e0, e, handler, next;
  while (com_google_gwt_lang_asyncloaders_AsyncLoader4_callbacksHead) {
    handler = com_google_gwt_core_client_GWT_sUncaughtExceptionHandler;
    next = com_google_gwt_lang_asyncloaders_AsyncLoader4_callbacksHead;
    com_google_gwt_lang_asyncloaders_AsyncLoader4_callbacksHead = com_google_gwt_lang_asyncloaders_AsyncLoader4_callbacksHead.com_google_gwt_lang_asyncloaders_AsyncLoader4_1_1Callback_next;
    !com_google_gwt_lang_asyncloaders_AsyncLoader4_callbacksHead && (com_google_gwt_lang_asyncloaders_AsyncLoader4_callbacksTail = null);
    if (!handler) {
      com_sitecake_contentmanager_client_resources_LocaleProxyImpl$4_$onSuccess__Lcom_sitecake_contentmanager_client_resources_LocaleProxyImpl$4_2V(next.com_google_gwt_lang_asyncloaders_AsyncLoader4_1_1Callback_callback);
    }
     else {
      try {
        com_sitecake_contentmanager_client_resources_LocaleProxyImpl$4_$onSuccess__Lcom_sitecake_contentmanager_client_resources_LocaleProxyImpl$4_2V(next.com_google_gwt_lang_asyncloaders_AsyncLoader4_1_1Callback_callback);
      }
       catch ($e0) {
        $e0 = com_google_gwt_lang_Exceptions_caught__Ljava_lang_Object_2Ljava_lang_Object_2($e0);
        if (com_google_gwt_lang_Cast_instanceOf__Ljava_lang_Object_2IZ($e0, 67)) {
          e = $e0;
          handler.onUncaughtException__Ljava_lang_Throwable_2V(e);
        }
         else 
          throw $e0;
      }
    }
  }
}

function com_google_gwt_lang_asyncloaders_AsyncLoader4_AsyncLoader4__V(){
}

function com_google_gwt_lang_asyncloaders_AsyncLoader4_onLoad__V(){
  com_google_gwt_lang_asyncloaders_AsyncLoader4_instance = new com_google_gwt_lang_asyncloaders_AsyncLoader4_AsyncLoader4__V;
  com_google_gwt_core_client_impl_AsyncFragmentLoader_$fragmentHasLoaded__Lcom_google_gwt_core_client_impl_AsyncFragmentLoader_2IV((com_google_gwt_core_client_impl_AsyncFragmentLoader_$clinit__V() , com_google_gwt_core_client_impl_AsyncFragmentLoader_BROWSER_1LOADER), 4);
  !!$stats && $stats(com_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_$createStatsEvent__Lcom_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_2Ljava_lang_String_2Ljava_lang_String_2IILcom_google_gwt_core_client_JavaScriptObject_2($intern_2470, $intern_144, -1, -1));
  com_google_gwt_lang_asyncloaders_AsyncLoader4_instance.runCallbacks__V();
  !!$stats && $stats(com_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_$createStatsEvent__Lcom_google_gwt_core_client_impl_AsyncFragmentLoader$StandardLogger_2Ljava_lang_String_2Ljava_lang_String_2IILcom_google_gwt_core_client_JavaScriptObject_2($intern_2470, $intern_2360, -1, -1));
}

function com_google_gwt_lang_asyncloaders_AsyncLoader4(){
}

_ = com_google_gwt_lang_asyncloaders_AsyncLoader4_AsyncLoader4__V.prototype = com_google_gwt_lang_asyncloaders_AsyncLoader4.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_google_gwt_lang_asyncloaders_AsyncLoader4_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1google_1gwt_1lang_1asyncloaders_1AsyncLoader4_12_1classLit;
}
;
_.runCallbacks__V = function com_google_gwt_lang_asyncloaders_AsyncLoader4_runCallbacks__V(){
  com_google_gwt_lang_asyncloaders_AsyncLoader4_$runCallbacks__Lcom_google_gwt_lang_asyncloaders_AsyncLoader4_2V();
}
;
_.java_lang_Object_castableTypeMap$ = {};
function com_sitecake_contentmanager_client_resources_LocaleProxyImpl$4_$onSuccess__Lcom_sitecake_contentmanager_client_resources_LocaleProxyImpl$4_2V(this$static){
  this$static.com_sitecake_contentmanager_client_resources_LocaleProxyImpl$4_this$0.com_sitecake_contentmanager_client_resources_LocaleProxyImpl_messages = new com_sitecake_contentmanager_client_resources_MessagesDe_1_MessagesDe_1__V;
  com_sitecake_commons_client_util_SynchronizationBarrier_$release__Lcom_sitecake_commons_client_util_SynchronizationBarrier_2V(this$static.com_sitecake_contentmanager_client_resources_LocaleProxyImpl$4_this$0.com_sitecake_contentmanager_client_resources_LocaleProxyImpl_synchronizationBarrier);
}

function com_sitecake_contentmanager_client_resources_MessagesDe_1_MessagesDe_1__V(){
}

function com_sitecake_contentmanager_client_resources_MessagesDe_1(){
}

_ = com_sitecake_contentmanager_client_resources_MessagesDe_1_MessagesDe_1__V.prototype = com_sitecake_contentmanager_client_resources_MessagesDe_1.prototype = new java_lang_Object;
_.confirmUnsafeLogout__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_confirmUnsafeLogout__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2471).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.defaultStyle__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_defaultStyle__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2472).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.errorMessage1__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_errorMessage1__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2473).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.errorMessage2__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_errorMessage2__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2474).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.failedAttemptToSaveContent__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_failedAttemptToSaveContent__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2475).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.failedToPublishContent__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_failedToPublishContent__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2476).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.failedToUploadFiles__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_failedToUploadFiles__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2477).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.getClass__Ljava_lang_Class_2$ = function com_sitecake_contentmanager_client_resources_MessagesDe_1_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1sitecake_1contentmanager_1client_1resources_1MessagesDe_11_12_1classLit;
}
;
_.giveUpContentSaving__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_giveUpContentSaving__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2478).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidConfigParameter__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_invalidConfigParameter__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2(arg0, arg1){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2479), arg0), $intern_160), arg1), $intern_2370).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidMapInputCode__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_invalidMapInputCode__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2480).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidServiceResponse__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_invalidServiceResponse__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2372).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidUploadFileMaxSize__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_invalidUploadFileMaxSize__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2(arg0, arg1){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2481), arg0), $intern_2482), arg1), $intern_2375).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidUploadFileSelection__Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_invalidUploadFileSelection__Ljava_lang_String_2Ljava_lang_String_2(arg0){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2483), arg0), $intern_282).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidUploadFileType__Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_invalidUploadFileType__Ljava_lang_String_2Ljava_lang_String_2(arg0){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2484), arg0), $intern_2485).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.invalidVideoInputCode__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_invalidVideoInputCode__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2486).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.linkEditorMailtoLink__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_linkEditorMailtoLink__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2452).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.linkEditorWebLink__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_linkEditorWebLink__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2453).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.newTextItemDefaultContent__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_newTextItemDefaultContent__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2487).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.notificationDialogReadMore__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_notificationDialogReadMore__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2488).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteFlash__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_pasteFlash__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2489).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteHtml__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_pasteHtml__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2490).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteMap__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_pasteMap__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2491).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.pasteVideo__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_pasteVideo__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2492).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.publishButton__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_publishButton__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2493).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadAudio__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_selectFilesToUploadAudio__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2494).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadGeneric__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_selectFilesToUploadGeneric__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2495).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadImage__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_selectFilesToUploadImage__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2496).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.selectFilesToUploadVideo__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_selectFilesToUploadVideo__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2497).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.uncaughtException__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_uncaughtException__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2498).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.uploadingFiles__Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_uploadingFiles__Ljava_lang_String_2(){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2499).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.versionUpdateMessage__Ljava_lang_String_2Ljava_lang_String_2 = function com_sitecake_contentmanager_client_resources_MessagesDe_1_versionUpdateMessage__Ljava_lang_String_2Ljava_lang_String_2(arg0){
  return java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(java_lang_StringBuffer_$append__Ljava_lang_StringBuffer_2Ljava_lang_String_2Ljava_lang_StringBuffer_2(new java_lang_StringBuffer_StringBuffer__V, $intern_2500), arg0), $intern_2375).java_lang_StringBuffer_impl.com_google_gwt_core_client_impl_StringBufferImplAppend_string;
}
;
_.java_lang_Object_castableTypeMap$ = {};
var com_google_gwt_lang_ClassLiteralHolder_Lcom_1google_1gwt_1lang_1asyncloaders_1AsyncLoader4_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_1734, $intern_2501), com_google_gwt_lang_ClassLiteralHolder_Lcom_1sitecake_1contentmanager_1client_1resources_1MessagesDe_11_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_2121, $intern_2502);
$entry(com_google_gwt_lang_asyncloaders_AsyncLoader4_onLoad__V)();
